version: '3'

services:
    nginix-loadbalancer:
        image: jwilder/nginx-proxy:latest
        volumes:
            - //var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - DEFAULT_HOST=proxy
        ports:
            - "80:80"   
    node-app:
        build:
          context: ./nodeapp
        environment:
            - VIRTUAL_HOST=proxy
        ports:
            - "8080"
    flask-app:
        build:
          context: ./flaskapp
        environment:
            - VIRTUAL_HOST=proxy
        ports:
            - "5000"
    java-app:
        build:
          context: ./java
        environment:
            - VIRTUAL_HOST=proxy
        ports:
            - "8080"