version: "3.3"

services:
    web:
        image: nginx
        ports: 
            - 80
        volumes:
            - ./data:/home
            - ./test:/test
            - ./template.conf:/etc/nginx/conf.d/default.conf
