FROM python:3.8

MAINTAINER mihaiblandu25@gmail.com
USER daemon

LABEL com.example.version="0.0.1-beta"
LABEL vendor1="ACME Incorporated"
LABEL vendor2=ZENITH\ Incorporated
LABEL com.example.release-date="2015-02-12"
LABEL com.example.version.is-production=""

ADD README.MD .
RUN "echo $pwd"

WORKDIR /
