apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodespace
spec:
  selector:
    matchLabels:
      app: thenode
  template:
    metadata:
      labels:
        app: thenode
    spec:
      containers:
      - name: thenode
        image: thenode
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: thenode-service
spec:
  selector:
    app: thenode
  ports:
  - port: 5000
    targetPort: 5000

